### ISSUE TITLE
new tag for 4.3.1 hotfix release?

### ISSUE THREAD

**Issue by ryan-sg** [Barbatos/ioq3-for-UrbanTerror-4#56]
Can we get a tag for the 4.3.1 mark?  I presume its here: https://github.com/Barbatos/ioq3-for-UrbanTerror-4/commit/f6c287f290631c67be4ddace7371292c4d105e5f

Not a huge deal, but i could change to using the proper tagged version rather than explicit commit marker in my OpenBSD package :-)

**Comment by Barbatos** [comment]
Whoops, done!

Thank you Ryan. 👍
