### ISSUE TITLE
Request for using standardized build system

### ISSUE THREAD

**Issue by holgersson32644** [Barbatos/ioq3-for-UrbanTerror-4#67]
Hi,

I would like to create a package for my Linux distro and have much trouble with your self written Makefile (e.g. giving paths or changing CFLAGS).

Would you consider migrating to cmake or meson if you got some patches?

**Comment by Barbatos** [comment]
Hi,

Sure, CMake would be nice. However, we do not wish to spend much time working on this engine anymore so we won't do the move ourselves. I will happily merge a pull request for a new build system that works on all systems though. :)

**Comment by holgersson32644** [comment]
Great to hear! Don’t expect something too soon as other things keep me away from it right now - but I definetly plan it.

**Comment by holgersson32644** [comment]
Well, I tried, but I didn’t get it into something working (linking fails and honestly I don’t have any clue about windows or MacOS/OS X). I’ll attach my [CMakeLists.txt](https://github.com/Barbatos/ioq3-for-UrbanTerror-4/files/831025/CMakeLists.txt) with my current state if someone else wants to give it a shot.
However, I won’t work on this anymore, packaging with the custom Makefile is way easier (and I have a good draft to start from that).

**Comment by Barbatos** [comment]
That's too bad. Thank you for putting some time into this! Maybe someone else will have the courage to look into it in the future.
