### ISSUE TITLE
mousewheel scrolling during map download results in Client command overflow

### ISSUE THREAD

**Issue by The-spiki** [Barbatos/ioq3-for-UrbanTerror-4#76]
Tranc3r told me this happened to him, so I tested it myself.

If you are scrolling mousewheel (a lot) during map download (connect to server with current map that you do not have), it will result in Client command overflow when using Windows binaries (fs and m9)

On Linux it works without these problems.

So, it happens in Windows clients only, both FS build (ioQ3 1.35 urt 4.3.2-hotfix win-x86 Jan 6 2018) and m9 from Jan and Feb (build-100 and build-104)... but it is manifested differently.

With m9, got error popup window stating "Client command overflow" on which I can press OK and got back to main screen.

With fs build, the game gets minimized, window with log file appears and it grabs mouse focus, so it is little tricky to get out of it, copy the logs etc... and have to close the game window...
ERROR: Client command overflow
recursive error after: Client command overflow
Sys_QueEvent: overflow

I would understand if you would not bother fixing this bug as it is corner case requiring specific scenario, scrolling the mouse wheel vigorously during map download. I mean, who does that :)

**Comment by The-spiki** [comment]
FYI, I did cross post for this to m9 because it affected his build also
and he made fix, which you could use
https://github.com/mickael9/ioq3/issues/20

**Comment by Barbatos** [comment]
Thanks, fixed!
