### ISSUE TITLE
s_alttabmute suggestion

### ISSUE THREAD

**Issue by BidyBiddle** [Barbatos/ioq3-for-UrbanTerror-4#77]
Would be handy to add a CVAR that allows you to mute UrT sound if desired when alt tabbed.

P5yc0runn3r had written such a functionality, dunno if it's findable somewhere.

**Comment by Barbatos** [comment]
The cvar exists in the official engine since 2014, it is named s_alttabmute. Is it what you were looking for?

**Comment by BidyBiddle** [comment]
Yup, indeed, mixed some things up.
